### ISSUE TITLE
Error Message : Uncaught TypeError: Cannot read properties of undefined (reading 'split')

### ISSUE THREAD

**Issue by ArneSnackaert** [ant-media/videojs-webrtc-plugin#6]
I'm getting following Error when loading the script.

Uncaught TypeError: Cannot read properties of undefined (reading 'split')
    at t.i.getUrlParameter (videojs-webrtc-plugin.min.js:2:12622)
    at t.i.initiateWebRTCAdaptor (videojs-webrtc-plugin.min.js:2:9940)
    at new t (videojs-webrtc-plugin.min.js:2:9323)
    at r (video.min.js:20:179321)
    at o.antmediaWebrtc (video.min.js:20:178778)
    at test.html:21:10

My Script:

<body>

<script src="node_modules\video.js\dist\video.min.js"></script>
<script src="node_modules\@antmedia\videojs-webrtc-plugin\dist\videojs-webrtc-plugin.min.js"></script>
<video id="vid1" class="video-js">

</video>

<script>
  var player = videojs('vid1');

  player.antmediaWebrtc({
    streamUrl: "ws://"server":5080/"App"/"Stream".webrtc",
    iceServers: '[ { "urls": "stun:stun1.l.google.com:19302" } ]',
  });
  player.on('ant-error', function(event, errors) {
    console.log(errors);
  });
</script>
</body>

**Comment by golgetahir** [comment]
Hi @ArneSnackaert 

We have not completed the implementation of this plug-in yet ( had some problems with developers ), we are about to finish it though. I am converting the structure to another thing for source handling, you can see the latest commits about that. I do understand this error and while converting it will be resolved. Thanks for keeping up with us so fast!
